package dev.wrrulosdev.mcpclient.client.mixins.gui;

import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.ChatComponent;
import net.minecraft.client.multiplayer.chat.GuiMessage;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(ChatComponent.class)
public abstract class ChatComponentMixin {

    @Shadow @Final private Minecraft minecraft;
    @Shadow private int getWidth() { return 0; }
    @Shadow private double getScale() { return 0.0; }

    @Unique
    private double smoothOffset = 0.0;
    @Unique
    private long lastTime = 0;
    @Unique
    private boolean isRefreshing = false;

    /**
     * Marks the beginning of a chat refresh operation.
     * During refreshes, incoming messages should not contribute to the animation
     * offset calculation since they are not newly received messages.
     *
     * @param ci Callback information for the injection point
     */
    @Inject(method = "refreshTrimmedMessages", at = @At("HEAD"))
    private void onRefreshStart(CallbackInfo ci) {
        this.isRefreshing = true;
    }

    /**
     * Marks the completion of a chat refresh operation and resets animation state.
     *
     * @param ci Callback information for the injection point
     */
    @Inject(method = "refreshTrimmedMessages", at = @At("TAIL"))
    private void onRefreshEnd(CallbackInfo ci) {
        this.isRefreshing = false;
        this.smoothOffset = 0.0;
    }

    /**
     * Resets the animation offset when chat messages are cleared.
     *
     * @param history Whether chat history should also be cleared
     * @param ci Callback information for the injection point
     */
    @Inject(method = "clearMessages", at = @At("HEAD"))
    private void onClearMessages(boolean history, CallbackInfo ci) {
        this.smoothOffset = 0.0;
    }

    /**
     * Calculates the amount of vertical offset that should be applied when a new
     * message is added to the visible chat queue.
     * <p>
     * The offset is based on the number of wrapped lines generated by the message
     * and the current chat line spacing configuration.
     *
     * @param message The message being added to the display queue
     * @param ci Callback information for the injection point
     */
    @Inject(method = "addMessageToDisplayQueue", at = @At("HEAD"))
    private void onAddMessage(GuiMessage message, CallbackInfo ci) {
        if (!this.isRefreshing && this.minecraft.font != null) {
            int maxWidth = net.minecraft.util.Mth.floor((double) this.getWidth() / this.getScale());
            int linesAdded = message.splitLines(this.minecraft.font, maxWidth).size();

            double chatLineSpacing = (Double) this.minecraft.options.chatLineSpacing().get();
            int entryHeight = (int) ((double) 9.0F * (chatLineSpacing + 1.0));

            this.smoothOffset += (linesAdded * entryHeight);
        }
    }

    /**
     * Applies a smooth translation animation to the chat render state.
     * The offset gradually decreases using exponential decay, producing a fluid
     * scrolling effect whenever new messages enter the chat window.
     *
     * @param graphics Chat graphics access used to modify rendering transforms
     * @param screenHeight Current screen height
     * @param ticks Current client tick count
     * @param displayMode Active chat display mode
     * @param ci Callback information for the injection point
     */
    @Inject(
        method = "extractRenderState(Lnet/minecraft/client/gui/components/ChatComponent$ChatGraphicsAccess;IILnet/minecraft/client/gui/components/ChatComponent$DisplayMode;)V",
        at = @At(
            value = "INVOKE",
            target = "Lnet/minecraft/client/gui/components/ChatComponent$ChatGraphicsAccess;updatePose(Ljava/util/function/Consumer;)V",
            shift = At.Shift.AFTER
        )
    )
    private void applySmoothAnimation(
        ChatComponent.ChatGraphicsAccess graphics,
        int screenHeight,
        int ticks,
        ChatComponent.DisplayMode displayMode,
        CallbackInfo ci
    ) {
        long now = System.currentTimeMillis();

        if (this.lastTime == 0) {
            this.lastTime = now;
        }

        long delta = now - this.lastTime;
        this.lastTime = now;

        if (!displayMode.foreground && this.smoothOffset > 0.0) {
            this.smoothOffset *= Math.exp(-delta * 0.015);

            if (this.smoothOffset < 0.1) {
                this.smoothOffset = 0.0;
            }

            final float visualOffset = (float) this.smoothOffset;

            graphics.updatePose(
                pose -> pose.translate(0.0F, visualOffset)
            );
        } else if (displayMode.foreground) {
            this.smoothOffset = 0.0;
        }
    }
}